### ISSUE TITLE
Request: Seq2Seq example (not BERT)

### ISSUE THREAD

**Issue by cpury** [phohenecker/pytorch-transformer#1]
Awesome package, thanks a lot!

I'm trying to build a seq2seq model similar to GPT-2 off it. Your BERT-example code was very helpful. It would be amazing to get something similar for Seq2Seq, e.g. machine translation. Especially how to build the training procedure is not quite clear to me.

**Comment by phohenecker** [comment]
Thank you so much. Great to hear that it's actually useful for other people as well :). Also, I'm happy to add an example of how to use it for GPT-like models. I'll try to do that until tomorrow.

**Comment by phohenecker** [comment]
Hi! Sorry for the late reply.

[Here](https://github.com/phohenecker/pytorch-transformer/blob/master/examples/gpt_pretraining.py) is an example that illustrates how to pretrain an encoder GPT style. For GPT-2 in particular, you'd also have to adjust the encoder itself accordingly, which should be straightforward, though. If you are looking into an NMT problem, however, then I'd suggest that you also check out [this recent FAIR paper](https://arxiv.org/abs/1901.07291).
